# Generated by Django 3.2 on 2021-05-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors')),
            ],
        ),
        migrations.CreateModel(
            name='FilmReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user_review', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(default='')),
                ('premiere', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('film_reviews', models.ManyToManyField(through='basic.FilmReviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Drama'), (6, 'rom-coms'), (5, 'romantic'), (4, 'action'), (8, 'musicals'), (7, 'adventure'), (0, 'Undefined'), (1, 'Comedy')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('role_photo', models.ImageField(blank=True, null=True, upload_to='roles')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.actors')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_title', to='basic.films')),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.genre'),
        ),
        migrations.AddField(
            model_name='films',
            name='roles',
            field=models.ManyToManyField(through='basic.Roles', to='basic.Actors'),
        ),
        migrations.AddField(
            model_name='filmreviews',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.films'),
        ),
        migrations.AddField(
            model_name='filmreviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
