# Generated by Django 3.2 on 2021-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(6, 'rom-coms'), (8, 'musicals'), (5, 'romantic'), (2, 'Drama'), (3, 'Sci-fi'), (0, 'Undefined'), (4, 'action'), (7, 'adventure'), (1, 'Comedy')], default=0),
        ),
    ]
