# Generated by Django 3.2 on 2021-05-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (5, 'romantic'), (1, 'Comedy'), (6, 'rom-coms'), (7, 'adventure'), (0, 'Undefined'), (2, 'Drama'), (8, 'musicals'), (4, 'action')], default=0),
        ),
    ]
