# Generated by Django 3.2 on 2021-05-09 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20210507_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (5, 'romantic'), (6, 'rom-coms'), (2, 'Drama'), (4, 'action'), (8, 'musicals'), (1, 'Comedy'), (0, 'Undefined'), (7, 'adventure')], default=0),
        ),
        migrations.AlterField(
            model_name='roles',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_role', to='basic.actors'),
        ),
    ]
