# Generated by Django 3.2 on 2021-05-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20210510_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='roles',
            field=models.ManyToManyField(related_name='role', through='basic.Roles', to='basic.Actors'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Drama'), (7, 'adventure'), (3, 'Sci-fi'), (8, 'musicals'), (4, 'action'), (0, 'Undefined'), (1, 'Comedy'), (6, 'rom-coms'), (5, 'romantic')], default=0),
        ),
    ]
