# Generated by Django 3.2 on 2021-05-10 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0005_auto_20210510_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmreviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_FilmReviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Drama'), (4, 'action'), (0, 'Undefined'), (7, 'adventure'), (1, 'Comedy'), (5, 'romantic'), (6, 'rom-coms'), (3, 'Sci-fi'), (8, 'musicals')], default=0),
        ),
    ]
