# Generated by Django 3.2 on 2021-05-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20210510_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='role_photo',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Drama'), (1, 'Comedy'), (3, 'Sci-fi'), (8, 'musicals'), (0, 'Undefined'), (4, 'action'), (7, 'adventure'), (5, 'romantic'), (6, 'rom-coms')], default=0),
        ),
    ]
