# Generated by Django 3.2 on 2021-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20210510_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmreviews',
            name='seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Undefined'), (5, 'romantic'), (2, 'Drama'), (6, 'rom-coms'), (3, 'Sci-fi'), (1, 'Comedy'), (7, 'adventure'), (4, 'action'), (8, 'musicals')], default=0),
        ),
    ]
