# Generated by Django 3.2 on 2021-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20210510_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Drama'), (3, 'Sci-fi'), (1, 'Comedy'), (7, 'adventure'), (6, 'rom-coms'), (0, 'Undefined'), (5, 'romantic'), (8, 'musicals'), (4, 'action')], default=0),
        ),
    ]
