# Generated by Django 3.2 on 2021-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20210523_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Drama'), (3, 'Sci-fi'), (5, 'romantic'), (7, 'adventure'), (8, 'musicals'), (4, 'action'), (6, 'rom-coms'), (0, 'Undefined'), (1, 'Comedy')], default=0),
        ),
    ]
