# Generated by Django 3.2 on 2021-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(7, 'adventure'), (8, 'musicals'), (0, 'Undefined'), (1, 'Comedy'), (6, 'rom-coms'), (4, 'action'), (2, 'Drama'), (3, 'Sci-fi'), (5, 'romantic')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profilepic.jpg', null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Not your business', max_length=100),
        ),
    ]
