# Generated by Django 3.2.6 on 2022-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_auto_20210604_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Comedy'), (3, 'Sci-fi'), (6, 'rom-coms'), (7, 'adventure'), (4, 'action'), (8, 'musicals'), (5, 'romantic'), (0, 'Undefined'), (2, 'Drama')], default=0),
        ),
    ]
