# Generated by Django 3.2.6 on 2022-03-05 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_auto_20210604_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='scrapped_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Drama'), (1, 'Comedy'), (4, 'action'), (8, 'musicals'), (7, 'adventure'), (3, 'Sci-fi'), (5, 'romantic'), (0, 'Undefined'), (6, 'rom-coms')], default=0),
        ),
    ]
