# Generated by Django 3.2.6 on 2022-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(7, 'adventure'), (6, 'rom-coms'), (2, 'Drama'), (4, 'action'), (1, 'Comedy'), (3, 'Sci-fi'), (5, 'romantic'), (0, 'Undefined'), (8, 'musicals')], default=0),
        ),
    ]
